### ISSUE TITLE
variantfishtest

### ISSUE THREAD

**Issue by ChessGUI** [ianfab/variantfishtest#1]
Hallo, ist Deine Anwendung eine graphische Benutzeroberfläche wie WinBoard ,http://hgm.nubati.net/WinBoard-AA.zip auf der UCI-kompatible Schachprogramme Engine-Matches gegeneinander austragen können? Welche Varianten werden dabei unterstützt?

**Comment by ianfab** [comment]
Hallo. Das ist keine GUI, sondern ein Kommandozeilen-basiertes Skript zum Testen von Änderungen an einem [Fork von Stockfish](https://github.com/ddugovic/Stockfish), der Schachvarianten unterstützt, indem Matches zwischen verschiedenen Versionen der Engine gespielt werden. Das Skript selbst testet nicht, ob die Züge legal sind (um beliebige Varianten zu unterstützen), sondern gibt sie einfach an die Engine weiter. Sofern eine Engine die `UCI_Variant`-Option unterstützt, sollte es aber auch mit anderen Engines als Stockfish funktionieren, allerdings habe ich das bisher nicht getestet.
