### ISSUE TITLE
About the result explanation.

### ISSUE THREAD

**Issue by PikaCat-OuO** [ianfab/variantfishtest#4]
If I run the test with the command line:python variantfishtest.py fairy-stockfish.exe --e1-options EvalFile=xiangqi-new.nnue fairy-stockfish.exe --e2-options EvalFile=xiangqi-old.nnue -t 10000 -i 100 -v xiangqi -b -n 10

Suppose I get a result like: ELO +abc ......
So which explanation is correct?
A: xiangqi-new.nnue is abc ELO stronger than xiangqi-old.nnue
B: xiangqi-new.nnue is abc ELO weaker than xiangqi-old.nnue

**Comment by ianfab** [comment]
It's A. The results are written as engine1 vs engine2.

**Comment by PikaCat-OuO** [comment]
BTW, may I ask the meaning of  +-x(95%) and LOS: x%?
It is the first time I try to test something like this and I can't figure out the meaning of these terms.

**Comment by ianfab** [comment]
* The value before 95% refers to the statistical uncertainty at 95% [confidence level](https://en.wikipedia.org/wiki/Confidence_interval).
* LOS is the [likely of superiority](https://www.chessprogramming.org/Match_Statistics#Likelihood_of_superiority).

Might be a good idea to extend the readme. For a long time I was the only user of this script, so I didn't feel the need to improve documentation, and only recently others started using it.
