### ISSUE TITLE
Whether variants need a different argument K for elo calculation.

### ISSUE THREAD

**Issue by meet-ai** [ianfab/variantfishtest#5]
Hi Thank you for jobs in chess. It is great!
I notice that variantfishtest calculates elo with the following method.
![image](https://user-images.githubusercontent.com/43718138/197147687-14bfaa60-6c12-457d-a718-1b314d4cce58.png)

then my question is , whether  variants  need a different argument of K. (in chess it is 4)

**Comment by ianfab** [comment]
The Elo system isn't really bound to chess in any way, so the answer is no. You can of course arbitrarily scale the range by tweaking the constants, but that would be more or less meaningless.
